val offsetN: string
val end_offsetN: string
val idN: string
val comment: Markup.t
val keyword1: Markup.t
val declaration: Markup.t
val proof_declaration: Markup.t
val qed: Markup.t
val string: Markup.t
val delimiter: Markup.t
val initN: string
val statusN: string
val reportN: string
val report: Markup.t
val writelnN: string
val warningN: string
val errorN: string
val protocolN: string
val functionN: string
val ready: Properties.t
val assign_update: Properties.t
val removed_versions: Properties.t
